// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Account struct {
	ID        int32
	Owner     string
	Balance   int32
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int32
	AccountID int32
	// can be negative or positive
	Amount    int32
	CreatedAt time.Time
}

type Session struct {
	ID           int32
	Username     string
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type Transfer struct {
	ID            int32
	FromAccountID int32
	ToAccountID   int32
	// must be positive
	Amount    int32
	CreatedAt time.Time
}

type User struct {
	Username          string
	HashedPassword    string
	FullName          string
	Email             string
	IsEmailVerified   bool
	PasswordChangedAt time.Time
	CreatedAt         time.Time
}

type VerifyEmail struct {
	ID         int32
	Username   string
	Email      string
	SecretCode string
	IsUsed     bool
	CreatedAt  time.Time
	ExpiredAt  time.Time
}
