// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: verify_email.sql

package db

import (
	"context"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :exec
INSERT INTO verify_emails (
    username,
    email,
    secret_code
) VALUES (
             ?, ?, ?
         )
`

type CreateVerifyEmailParams struct {
	Username   string
	Email      string
	SecretCode string
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) error {
	_, err := q.db.ExecContext(ctx, createVerifyEmail, arg.Username, arg.Email, arg.SecretCode)
	return err
}

const updateVerifyEmail = `-- name: UpdateVerifyEmail :exec
UPDATE verify_emails
SET
    is_used = TRUE
WHERE
        id = @id
  AND secret_code = @secret_code
  AND is_used = FALSE
  AND expired_at > now()
`

func (q *Queries) UpdateVerifyEmail(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateVerifyEmail)
	return err
}
