// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"
	"project_T4/service_account/account/pb_account"

	grpc "google.golang.org/grpc"

	"github.com/stretchr/testify/mock"
)

// MockAccountBankClient is an autogenerated mocks type for the AccountBankClient type
type MockAccountBankClient struct {
	mock.Mock
}

type MockAccountBankClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountBankClient) EXPECT() *MockAccountBankClient_Expecter {
	return &MockAccountBankClient_Expecter{mock: &_m.Mock}
}

// GetAccount provides a mocks function with given fields: ctx, in, opts
func (_m *MockAccountBankClient) GetAccount(ctx context.Context, in *pb_account.GetAccountRequest, opts ...grpc.CallOption) (*pb_account.GetAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb_account.GetAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb_account.GetAccountRequest, ...grpc.CallOption) (*pb_account.GetAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb_account.GetAccountRequest, ...grpc.CallOption) *pb_account.GetAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb_account.GetAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb_account.GetAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountBankClient_GetAccount_Call is a *mocks.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockAccountBankClient_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mocks.On call
//  - ctx context.Context
//  - in *pb_account.GetAccountRequest
//  - opts ...grpc.CallOption
func (_e *MockAccountBankClient_Expecter) GetAccount(ctx interface{}, in interface{}, opts ...interface{}) *MockAccountBankClient_GetAccount_Call {
	return &MockAccountBankClient_GetAccount_Call{Call: _e.mock.On("GetAccount",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAccountBankClient_GetAccount_Call) Run(run func(ctx context.Context, in *pb_account.GetAccountRequest, opts ...grpc.CallOption)) *MockAccountBankClient_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pb_account.GetAccountRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAccountBankClient_GetAccount_Call) Return(_a0 *pb_account.GetAccountResponse, _a1 error) *MockAccountBankClient_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountBankClient_GetAccount_Call) RunAndReturn(run func(context.Context, *pb_account.GetAccountRequest, ...grpc.CallOption) (*pb_account.GetAccountResponse, error)) *MockAccountBankClient_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountBankClient creates a new instance of MockAccountBankClient. It also registers a testing interface on the mocks and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountBankClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountBankClient {
	mock := &MockAccountBankClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
